from enum import Enum


class KniffelOptions(Enum):
    ONES = 1
    TWOS = 2
    THREES = 3
    FOURS = 4
    FIVES = 5
    SIXES = 6
    THREE_TIMES = 7
    FOUR_TIMES = 8
    FULL_HOUSE = 9
    SMALL_STREET = 10
    LARGE_STREET = 11
    KNIFFEL = 12
    CHANCE = 13

    ONES_SLASH = 14
    TWOS_SLASH = 15
    THREES_SLASH = 16
    FOURS_SLASH = 17
    FIVES_SLASH = 18
    SIXES_SLASH = 19
    THREE_TIMES_SLASH = 20
    FOUR_TIMES_SLASH = 21
    FULL_HOUSE_SLASH = 22
    SMALL_STREET_SLASH = 23
    LARGE_STREET_SLASH = 24
    KNIFFEL_SLASH = 25
    CHANCE_SLASH = 26
    DEFAULT = 27
