on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script:
        - python pip install keras-rl
        - python pip install keras-rl2
        - python pip install gym
        - python pip install sympy
        - python /inputs/repo/ai/commands/train.py
      image: tensorflow/tensorflow:1.14.0-py3
