on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  RunScript:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: 
        - pip install pip install keras-rl
        - pip install keras-rl2
        - pip install gym
        - pip install sympy
        - python ai\commands\train.py
      image: tensorflow/tensorflow:1.14.0-py3
